sonar.projectKey=notes-app
sonar.sources=backend/src,frontend/notes-app/src
sonar.tests=backend/tests,frontend/notes-app/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/dist-test/**,**/coverage/**,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/main.tsx,**/vite-env.d.ts,**/server.ts,**/config/db.ts,**/pages/**,**/api/**,**/context/**,**/App.tsx
sonar.javascript.lcov.reportPaths=.sonar/coverage/backend-lcov.info,.sonar/coverage/frontend-lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
